src = [
    'libtiff/tif_aux.c',
    'libtiff/tif_close.c',
    'libtiff/tif_codec.c',
    'libtiff/tif_compress.c',
    'libtiff/tif_dir.c',
    'libtiff/tif_dirinfo.c',
    'libtiff/tif_dirread.c',
    'libtiff/tif_dirwrite.c',
    'libtiff/tif_dumpmode.c',
    'libtiff/tif_error.c',
    'libtiff/tif_fax3.c',
    'libtiff/tif_fax3sm.c',
    'libtiff/tif_flush.c',
    'libtiff/tif_hash_set.c',
    'libtiff/tif_jpeg.c',
    'libtiff/tif_luv.c',
    'libtiff/tif_lzw.c',
    'libtiff/tif_next.c',
    'libtiff/tif_open.c',
    'libtiff/tif_packbits.c',
    'libtiff/tif_pixarlog.c',
    'libtiff/tif_predict.c',
    'libtiff/tif_read.c',
    'libtiff/tif_strip.c',
    'libtiff/tif_swab.c',
    'libtiff/tif_thunder.c',
    'libtiff/tif_tile.c',
    'libtiff/tif_warning.c',
    'libtiff/tif_win32.c',
    'libtiff/tif_write.c',
    'libtiff/tif_zip.c'
]

tiff_32 = static_library('tiff_32', [headers, src],
    include_directories : [incdir, '../../include/msvcrt', 'libtiff', '.', '../../libs/jpeg', '../../libs/zlib'],
    c_args : extra_flags_lib_32 + ['-D_UCRT', '-DFAR=', '-DZ_SOLO', '-D_WIN32'],
    pic : true,
    native : false,
    build_by_default : meson.is_cross_build(),
)

tiff_64 = static_library('tiff_64', [headers, src],
    include_directories : [incdir, '../../include/msvcrt', 'libtiff', '.', '../../libs/jpeg', '../../libs/zlib'],
    c_args : extra_flags_lib_64 + ['-D_UCRT', '-DFAR=', '-DZ_SOLO', '-D__WINE_PE_BUILD'],
    native : false,
    build_by_default : meson.is_cross_build(),
)
