w_src = files(
    'main.c',
)

u_src = files(
    'bitblt.c',
    'bitmap.c',
    'brush.c',
    'class.c',
    'clipboard.c',
    'clipping.c',
    'cursoricon.c',
    'd3dkmt.c',
    'dc.c',
    'dce.c',
    'defwnd.c',
    'dib.c',
    'dibdrv/bitblt.c',
    'dibdrv/dc.c',
    'dibdrv/graphics.c',
    'dibdrv/objects.c',
    'dibdrv/opengl.c',
    'dibdrv/primitives.c',
    'driver.c',
    'emfdrv.c',
    'font.c',
    'freetype.c',
    'gdiobj.c',
    'hook.c',
    'imm.c',
    'input.c',
    'mapping.c',
    'menu.c',
    'message.c',
    'opentype.c',
    'painting.c',
    'palette.c',
    'path.c',
    'pen.c',
    'printdrv.c',
    'rawinput.c',
    'region.c',
    'scroll.c',
    'spy.c',
    'syscall.c',
    'sysparams.c',
    'systray.c',
    'vertical.c',
    'vulkan.c',
    'window.c',
    'winstation.c',
)

dlls += {
    'win32u' : {
        'src' : w_src,
        'extra_args' : ['-I../include/msvcrt', '-D_MSVCR_VER=0', '-D_WIN32U_'],
        'idl_h' : [],
        'idl_c' : [],
        'res' : [],
        'obj' : [],
        'deps': [
            'winecrt0',
            'msvcrt',
            'kernel32',
            'ntdll',
        ],
        'so' : {
            'src' : u_src,
            'extra_args' : ['-I/usr/include/freetype2', '-I../dlls/win32u', '-D_WIN32U_'],
            'deps' : [freetype2, pthread, libm],
            'link' : ['ntdll_so'],
        },
    }
}
