src = [
    'd2d.c',
    'uuid.c'
]

uuid_32 = static_library('uuid_32', [headers, src],
    include_directories : incdir,
    c_args : extra_flags_32,
    pic : true,
    native : false,
    build_by_default : meson.is_cross_build(),
)

uuid_64 = static_library('uuid_64', [headers, src],
    include_directories : incdir,
    c_args : extra_flags_64,
    native : false,
    build_by_default : meson.is_cross_build(),
)
