subdir('adsiid')
subdir('capstone')
subdir('compiler-rt')
subdir('dmoguids')
subdir('dxerr8')
subdir('dxerr9')
subdir('dxguid')
#subdir('faudio')
#subdir('fluidsynth')
subdir('gsm')
subdir('jpeg')
#subdir('jxr')
#subdir('lcms2')
#subdir('ldap')
subdir('mfuuid')
#subdir('mpg123')
subdir('musl')
subdir('png')
subdir('strmbase')
subdir('strmiids')
subdir('tiff')
subdir('tomcrypt')
subdir('uuid')
subdir('vkd3d')
subdir('wbemuuid')
subdir('wmcodecdspuuid')
#subdir('xml2')
#subdir('xslt')
subdir('zlib')
