# Essential reusable core idls
idl_h = files(
  'shobjidl_core.idl',
  'objectarray.idl',
  'structuredquerycondition.idl',
  'propsys.idl',
  'comcat.idl',
  'shobjidl.idl',
  'shtypes.idl',
  'shldisp.idl',
  'servprov.idl',
  'docobj.idl',
  'msxml.idl',
  'urlmon.idl',
  'ocidl.idl',
  'exdisp.idl',
  'wtypes.idl',
  'unknwn.idl',
  'oleacc.idl',
  'oleidl.idl',
  'objidl.idl',
  'oaidl.idl',
  'propidl.idl',
  'objidlbase.idl',

  'wine/atsvc.idl',
  'wine/dcetypes.idl',
  'wine/epm.idl',
  'wine/fil_data.idl',
  'wine/iaccessible2.idl',
  'wine/irot.idl',
  'wine/irpcss.idl',
  'wine/itss.idl',
  'wine/mfinternal.idl',
  'wine/orpc.idl',
  'wine/plugplay.idl',
  'wine/schrpc.idl',
  'wine/svcctl.idl',
  'wine/winedxgi.idl',
)

# TODO: wipe this and spread them over all dlls
idls2 = files(
  'objidlbase.idl',

#  'access.idl',
  'activation.idl',
  'activaut.idl',
  'activdbg.idl',
  'activscp.idl',
  'amsi.idl',
  'amstream.idl',
  'amvideo.idl',
  'asptlb.idl',
  'asyncinfo.idl',
#  'asynot.idl',
#  'asysta.idl',
  'atliface.idl',
  'audioclient.idl',
  'audiopolicy.idl',
  'austream.idl',
#  'axcore.idl',
#  'axextend.idl',
  'bdaiface.idl',
#  'binres.idl',
  'bits1_5.idl',
  'bits2_0.idl',
  'bits2_5.idl',
  'bits3_0.idl',
  'bits5_0.idl',
  'bits.idl',
  'cdosys.idl',
#  'chprst.idl',
#  'cmdbas.idl',
#  'cmdpre.idl',
#  'cmdprp.idl',
#  'cmdstrm.idl',
#  'cmdtxt.idl',
#  'cmdwpr.idl',
  'cmnquery.idl',
#  'colinf.idl',
#  'colrst.idl',
  'comcat.idl',
  'commoncontrols.idl',
  'comsvcs.idl',
  'control.idl',
  'cordebug.idl',
  'cor.idl',
  'corsym.idl',
#  'crtrow.idl',
  'ctfutb.idl',
  'ctxtcall.idl',
#  'cvttyp.idl',
  'd2d1_1.idl',
  'd2d1_2.idl',
  'd2d1_3.idl',
  'd2d1effectauthor.idl',
  'd2d1effects_1.idl',
  'd2d1effects_2.idl',
  'd2d1effects.idl',
  'd2d1.idl',
  'd3d10_1.idl',
  'd3d10effect.idl',
  'd3d10.idl',
  'd3d10sdklayers.idl',
  'd3d10shader.idl',
  'd3d11_1.idl',
  'd3d11_2.idl',
  'd3d11_3.idl',
  'd3d11_4.idl',
  'd3d11.idl',
  'd3d11on12.idl',
  'd3d11sdklayers.idl',
  'd3d12.idl',
  'd3d12sdklayers.idl',
  'd3d12shader.idl',
  'd3d12video.idl',
  'd3d9on12.idl',
  'd3dcommon.idl',
  'd3dx11core.idl',
#  'dbccmd.idl',
#  'dbcses.idl',
#  'dbdsad.idl',
#  'dbinit.idl',
#  'dbprop.idl',
#  'dbs.idl',
  'dcommon.idl',
  'dcompanimation.idl',
  'dcomp.idl',
  'dcomptypes.idl',
  'ddstream.idl',
  'devenum.idl',
  'devicetopology.idl',
  'dhtmled.idl',
  'dimm.idl',
  'directmanipulation.idl',
  'dispatcherqueue.idl',
  'dispex.idl',
  'dmodshow.idl',
  'docobjectservice.idl',
  'docobj.idl',
  'documenttarget.idl',
  'downloadmgr.idl',
  'dragdropinterop.idl',
  'drmexternals.idl',
  'dvdif.idl',
  'dwrite_1.idl',
  'dwrite_2.idl',
  'dwrite_3.idl',
  'dwrite.idl',
  'dxgi1_2.idl',
  'dxgi1_3.idl',
  'dxgi1_4.idl',
  'dxgi1_5.idl',
  'dxgi1_6.idl',
  'dxgicommon.idl',
  'dxgidebug.idl',
  'dxgiformat.idl',
  'dxgi.idl',
  'dxgitype.idl',
  'dxva2api.idl',
  'dxvahd.idl',
#  'dyngraph.idl',
  'endpointvolume.idl',
#  'errrec.idl',
  'eventtoken.idl',
  'evr9.idl',
  'evr.idl',
  'exdisp.idl',
  'filter.idl',
  'fusion.idl',
  'gameux.idl',
#  'getdts.idl',
  'hlink.idl',
  'holographicspaceinterop.idl',
  'hrtfapoapi.idl',
  'hstring.idl',
  'htiface.idl',
  'htiframe.idl',
  'httprequest.idl',
  'iads.idl',
  'icftypes.idl',
  'icodecapi.idl',
  'ieautomation.idl',
  'iextag.idl',
  'iimgctx.idl',
  'imnact.idl',
  'imnxport.idl',
  'indexsrv.idl',
  'inputpaneinterop.idl',
  'inputscope.idl',
  'inseng.idl',
  'inspectable.idl',
  'ivectorchangedeventargs.idl',
  'mediaobj.idl',
  'medparam.idl',
  'metahost.idl',
  'mfd3d12.idl',
  'mfidl.idl',
  'mfmediaengine.idl',
  'mfobjects.idl',
  'mfplay.idl',
  'mfreadwrite.idl',
  'mftransform.idl',
  'mimeinfo.idl',
  'mimeole.idl',
  'mlang.idl',
  'mmc.idl',
  'mmdeviceapi.idl',
  'mmstream.idl',
  'mpegtype.idl',
  'msado15_backcompat.idl',
  'mscoree.idl',
  'msctf.idl',
  'msdadc.idl',
  'msdasc.idl',
  'mshtmhst.idl',
  'mshtml.idl',
  'msident.idl',
  'msinkaut.idl',
  'msopc.idl',
  'mstask.idl',
  'msxml2.idl',
  'msxml6.idl',
  'msxml.idl',
#  'mulres.idl',
  'natupnp.idl',
  'netcfgx.idl',
  'netcon.idl',
  'netfw.idl',
  'netlistmgr.idl',
  'oaidl.idl',
  'objectarray.idl',
  'objidl.idl',
  'objsafe.idl',
  'ocidl.idl',
  'ocmm.idl',
  'oleacc.idl',
  'oledb.idl',
  'oleidl.idl',
  'opcbase.idl',
#  'opcobjectmodel.idl',
  'opcparturi.idl',
#  'opnrst.idl',
  'optary.idl',
  'perhist.idl',
  'proofofpossessioncookieinfo.idl',
  'propidl.idl',
  'propsys.idl',
  'pstore.idl',
  'qedit.idl',
  'relogger.idl',
  'restrictederrorinfo.idl',
  'richole.idl',
  'roparameterizediid.idl',
#  'rowchg.idl',
#  'row.idl',
#  'rowpos.idl',
#  'rowpsc.idl',
#  'rstbas.idl',
#  'rstchg.idl',
#  'rstfnd.idl',
#  'rstidn.idl',
#  'rstinf.idl',
#  'rstloc.idl',
#  'rstnot.idl',
#  'rstscr.idl',
#  'rstupd.idl',
#  'rstxsc.idl',
  'rtworkq.idl',
#  'sapiaut.idl',
  'sapiddk.idl',
  'sapi.idl',
  'sensevts.idl',
  'servprov.idl',
#  'sesprp.idl',
  'shdeprecated.idl',
  'shimgdata.idl',
  'shldisp.idl',
  'shobjidl_core.idl',
  'shobjidl.idl',
  'shtypes.idl',
  'spatialaudioclient.idl',
#  'srcrst.idl',
  'strmif.idl',
  'structuredquerycondition.idl',
  'systemmediatransportcontrolsinterop.idl',
  'taskschd.idl',
  'textstor.idl',
  'thumbcache.idl',
  'tlogstg.idl',
  'tom.idl',
  'transact.idl',
#  'trnjoi.idl',
#  'trnlcl.idl',
#  'trnobj.idl',
  'txcoord.idl',
  'txdtc.idl',
  'uianimation.idl',
  'uiautomationclient.idl',
  'uiautomationcore.idl',
  'uiribbon.idl',
  'uiviewsettingsinterop.idl',
  'unknwn.idl',
  'urlhist.idl',
  'urlmon.idl',
  'videoacc.idl',
  'vmr9.idl',
#  'vmrender.idl',
  'vsbackup.idl',
  'vss.idl',
  'vswriter.idl',
  'wbemcli.idl',
  'wbemdisp.idl',
  'wbemprov.idl',
  'weakreference.idl',
  'wia_lh.idl',
  'wia_xp.idl',
  'wincodec.idl',
  'wincodecsdk.idl',
  'windows.applicationmodel.activation.idl',
  'windows.applicationmodel.background.idl',
  'windows.applicationmodel.core.idl',
  'windows.applicationmodel.datatransfer.dragdrop.core.idl',
  'windows.applicationmodel.datatransfer.dragdrop.idl',
  'windows.applicationmodel.datatransfer.idl',
  'windows.applicationmodel.idl',
  'windowscontracts.idl',
  'windows.data.json.idl',
  'windows.data.xml.dom.idl',
  'windows.devices.bluetooth.idl',
  'windows.devices.enumeration.idl',
  'windows.devices.geolocation.idl',
  'windows.devices.haptics.idl',
  'windows.devices.input.idl',
  'windows.devices.power.idl',
  'windows.devices.radios.idl',
  'windows.devices.usb.idl',
  'windows.foundation.collections.idl',
  'windows.foundation.idl',
  'windows.foundation.metadata.idl',
  'windows.foundation.numerics.idl',
  'windows.gaming.input.custom.idl',
  'windows.gaming.input.forcefeedback.idl',
  'windows.gaming.input.idl',
  'windows.gaming.ui.idl',
  'windows.globalization.idl',
  'windows.graphics.capture.idl',
  'windows.graphics.capture.interop.idl',
  'windows.graphics.directx.direct3d11.idl',
  'windows.graphics.directx.idl',
  'windows.graphics.effects.idl',
  'windows.graphics.holographic.idl',
  'windows.graphics.idl',
  'windows.graphics.imaging.idl',
  'windows.management.deployment.idl',
  'windows.media.capture.idl',
  'windows.media.closedcaptioning.idl',
  'windows.media.devices.idl',
  'windows.media.effects.idl',
  'windows.media.faceanalysis.idl',
  'windows.media.idl',
  'windows.media.render.idl',
  'windows.media.speechrecognition.idl',
  'windows.media.speechsynthesis.idl',
  'windows.networking.connectivity.idl',
  'windows.networking.idl',
  'windows.perception.spatial.idl',
  'windows.perception.spatial.surfaces.idl',
  'windows.security.authentication.onlineid.idl',
  'windows.security.authorization.appcapabilityaccess.idl',
  'windows.security.credentials.idl',
  'windows.security.credentials.ui.idl',
  'windows.security.cryptography.idl',
  'windows.security.enterprisedata.idl',
  'windows.security.exchangeactivesyncprovisioning.idl',
  'windows.security.isolation.idl',
  'windows.storage.fileproperties.idl',
  'windows.storage.idl',
  'windows.storage.search.idl',
  'windows.storage.streams.idl',
  'windows.system.idl',
  'windows.system.power.idl',
  'windows.system.profile.idl',
  'windows.system.profile.systemmanufacturers.idl',
  'windows.system.threading.idl',
  'windows.system.userprofile.idl',
  'windows.ui.composition.idl',
  'windows.ui.composition.interop.idl',
  'windows.ui.core.idl',
  'windows.ui.idl',
  'windows.ui.input.idl',
  'windows.ui.notifications.idl',
  'windows.ui.viewmanagement.idl',
  'windows.ui.xaml.hosting.desktopwindowxamlsource.idl',
  'windows.ui.xaml.idl',
  'windows.ui.xaml.interop.idl',
  'winsxs.idl',
  'wmcodecdsp.idl',
  'wmdrmsdk.idl',
  'wmiutils.idl',
  'wmp.idl',
  'wmprealestate.idl',
  'wmpservices.idl',
  'wmsbuffer.idl',
  'wmsdkidl.idl',
  'wmsecure.idl',
  'wpcapi.idl',
  'wsdbase.idl',
  'wsddisco.idl',
  'wsdxml.idl',
  'wtypes.idl',
  'wuapi.idl',
  'xamlom.idl',
  'xapo.idl',
  'xaudio2fx.idl',
  'xaudio2.idl',
#  'xmldom.idl',
#  'xmldso.idl',
  'xmllite.idl',
  'xpsobjectmodel_1.idl',
  'xpsobjectmodel.idl',


  'wine/atsvc.idl',
  'wine/dcetypes.idl',
  'wine/epm.idl',
  'wine/fil_data.idl',
  'wine/iaccessible2.idl',
  'wine/irot.idl',
  'wine/irpcss.idl',
  'wine/itss.idl',
  'wine/mfinternal.idl',
  'wine/orpc.idl',
  'wine/plugplay.idl',
  'wine/schrpc.idl',
  'wine/svcctl.idl',
  'wine/winedxgi.idl',
)

headers = gen_idl_h.process(idl_h, preserve_path_from : meson.current_source_dir())
